version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: neha676/insurance-frontend:latest
    ports:
      - "2000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Docker-file
    image: neha676/insurance-backend:latest
    ports:
      - "8089:8089"
    environment:
      SERVER_PORT: 8089
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/insurance_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: insurance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insurance_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

